// <auto-generated />
namespace OgrenciKayit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delimg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delimg));
        
        string IMigrationMetadata.Id
        {
            get { return "202109161238252_del-img"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
